export const BOOKS_LIST_REQUEST = 'BOOKS_LIST_REQUEST';
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS';
export const BOOKS_LIST_FAIL = 'BOOKS_LIST_FAIL';

export const BOOKS_DETAILS_REQUEST = 'BOOKS_DETAILS_REQUEST';
export const BOOKS_DETAILS_SUCCESS = 'BOOKS_DETAILS_SUCCESS';
export const BOOKS_DETAILS_RESET = 'BOOKS_DETAILS_RESET';
export const BOOKS_DETAILS_FAIL = 'BOOKS_DETAILS_FAIL';

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET';

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST';
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS';
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL';
export const BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';

export const BOOK_CREATE_REVIEW_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_REVIEW_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_REVIEW_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_REVIEW_RESET = 'BOOK_CREATE_RESET';

export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST';
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS';
export const REVIEW_UPDATE_FAIL = 'REVIEW_UPDATE_FAIL';
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET';
