export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const FAVORITE_ADD_ITEM = 'FAVORITE_ADD_ITEM';
export const FAVORITE_REMOVE_ITEM = 'FAVORITE_REMOVE_ITEM';
