'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert(
    'Images',
    [
      {
        bookId:1,
        url:'https://www.alpinabook.ru/upload/setka-editor/608/608dd4e051232813f2064b7e3d07a771.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:1,
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7yoEnkacVSP_4F8bkpKdodJlvoJUd3Ulow&usqp=CAU',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:1,
        url:'https://cutt.ly/8h2QDRt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:2,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:2,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:2,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:3,
        url:'https://www.alpinabook.ru/upload/setka-editor/608/608dd4e051232813f2064b7e3d07a771.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:3,
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7yoEnkacVSP_4F8bkpKdodJlvoJUd3Ulow&usqp=CAU',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:3,
        url:'https://cutt.ly/8h2QDRt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:4,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:4,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:4,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:5,
        url:'https://www.alpinabook.ru/upload/setka-editor/608/608dd4e051232813f2064b7e3d07a771.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:5,
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7yoEnkacVSP_4F8bkpKdodJlvoJUd3Ulow&usqp=CAU',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:5,
        url:'https://cutt.ly/8h2QDRt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:6,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:6,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:6,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        bookId:7,
        url:'https://www.alpinabook.ru/upload/setka-editor/608/608dd4e051232813f2064b7e3d07a771.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:7,
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7yoEnkacVSP_4F8bkpKdodJlvoJUd3Ulow&usqp=CAU',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:7,
        url:'https://cutt.ly/8h2QDRt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:8,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:8,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:8,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:9,
        url:'https://www.alpinabook.ru/upload/setka-editor/608/608dd4e051232813f2064b7e3d07a771.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:9,
        url:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7yoEnkacVSP_4F8bkpKdodJlvoJUd3Ulow&usqp=CAU',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:9,
        url:'https://cutt.ly/8h2QDRt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:10,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:10,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:11,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:12,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:13,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:14,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:15,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:16,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:17,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:18,
        url:'https://cutt.ly/Eh2Wkc5',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:19,
        url:'https://cutt.ly/uh2WeNc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        bookId:20,
        url:'https://cutt.ly/jh2Q9OD',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {},
  ),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Users', null, {}),
};