export const BOOKS_LIST_REQUEST = 'BOOKS_LIST_REQUEST';
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS';
export const BOOKS_LIST_FAIL = 'BOOKS_LIST_FAIL';

export const BOOKS_DETAILS_REQUEST = 'BOOKS_DETAILS_REQUEST';
export const BOOKS_DETAILS_SUCCESS = 'BOOKS_DETAILS_SUCCESS';
export const BOOKS_DETAILS_FAIL = 'BOOKS_DETAILS_FAIL';

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET';

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST';
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS';
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL';
export const BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET';

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';

export const BOOK_CREATE_REVIEW_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_REVIEW_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_REVIEW_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_REVIEW_RESET = 'BOOK_CREATE_RESET';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const FAVORITE_ADD_ITEM = 'FAVORITE_ADD_ITEM';
export const FAVORITE_REMOVE_ITEM = 'FAVORITE_REMOVE_ITEM';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';
